package awd.cloud.platform.servers.analyse.service.all;


import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class WXJS_zhxService {

    public Map<String,Object>  zhxQuery(){
        Map<String,Object> rt=new HashMap<>();
        Map<String,Object> map=new HashMap<>();
        Map<String,Object> data=new HashMap<>();
        Map<String,Object> list2=new HashMap<>();
        Map<String,Object> collection=new HashMap<>();
        Map<String,Object> popCllection=new HashMap<>();
        List< Map<String,Object>>  list=new ArrayList<>();
        List< Map<String,Object>>  header=new ArrayList<>();
        List< Map<String,Object>>  body=new ArrayList<>();
        List< Map<String,Object>>  label=new ArrayList<>();
        Map<String,Object> headermap1=new HashMap<>();
        headermap1.put("name","监所");
        headermap1.put("unit","");
        header.add(headermap1);
        Map<String,Object> headermap2=new HashMap<>();
        headermap2.put("name","投入资金开展信息化升级改造或建设项目情况");
        headermap2.put("unit","（是/否）");
        header.add(headermap2);
        Map<String,Object> headermap3=new HashMap<>();
        headermap3.put("name","监所开展信息化科技项目申报情况");
        headermap3.put("unit","（项目数）");
        header.add(headermap3);
        Map<String,Object> bodymap1=new HashMap<>();
        bodymap1.put("name","北京市第三看守所");
        bodymap1.put("value0","是");
        bodymap1.put("value1","全年1项");
        body.add(bodymap1);
        Map<String,Object> bodymap2=new HashMap<>();
        bodymap2.put("name","朝阳区看守所");
        bodymap2.put("value0","否");
        bodymap2.put("value1","全年2项");
        body.add(bodymap2);
        Map<String,Object> bodymap3=new HashMap<>();
        bodymap3.put("name","昌平区看守所");
        bodymap3.put("value0","是");
        bodymap3.put("value1","全年4项");
        body.add(bodymap3);
        Map<String,Object> bodymap4=new HashMap<>();
        bodymap4.put("name","东城区看守所");
        bodymap4.put("value0","是");
        bodymap4.put("value1","全年6项");
        body.add(bodymap4);
        Map<String,Object> bodymap5=new HashMap<>();
        bodymap5.put("name","北京市第一看守所");
        bodymap5.put("value0","是");
        bodymap5.put("value1","全年8项");
        body.add(bodymap5);
        Map<String,Object> bodymap6=new HashMap<>();
        bodymap6.put("name","昌平区看守所");
        bodymap6.put("value0","是");
        bodymap6.put("value1","0");
        body.add(bodymap6);
        Map<String,Object> bodymap7=new HashMap<>();
        bodymap7.put("name","东城区看守所");
        bodymap7.put("value0","是");
        bodymap7.put("value1","全年8项");
        body.add(bodymap7);
        Map<String,Object> bodymap8=new HashMap<>();
        bodymap8.put("name","朝阳区看守所");
        bodymap8.put("value0","是");
        bodymap8.put("value1","0");
        body.add(bodymap8);
        Map<String,Object> bodymap9=new HashMap<>();
        bodymap9.put("name","北京市第六看守所");
        bodymap9.put("value0","是");
        bodymap9.put("value1","全年5项");
        body.add(bodymap9);
        Map<String,Object> bodymap10=new HashMap<>();
        bodymap10.put("name","大兴区看守所");
        bodymap10.put("value0","是");
        bodymap10.put("value1","全年2项");
        body.add(bodymap10);
        Map<String,Object> listMap1=new HashMap<>();
        listMap1.put("name","信息化项目申报");
        listMap1.put("value","30");
        list.add(listMap1);
        Map<String,Object> listMap2=new HashMap<>();
        listMap2.put("name","电子脚扣");
        listMap2.put("value","50");
        list.add(listMap2);
        Map<String,Object> listMap3=new HashMap<>();
        listMap3.put("name","数据对接");
        listMap3.put("value","15");
        list.add(listMap3);
        Map<String,Object> listMap4=new HashMap<>();
        listMap4.put("name","安防系统建设");
        listMap4.put("value","35");
        list.add(listMap4);
        Map<String,Object> labelMap1=new HashMap<>();
        labelMap1.put("name","部署监控摄影机");
        labelMap1.put("value","1000");
        labelMap1.put("unit","台");
         label.add(labelMap1);
        Map<String,Object> labelMap2=new HashMap<>();
        labelMap2.put("name","信息化建设投资");
        labelMap2.put("value","2000");
        labelMap2.put("unit","亿");
        label.add(labelMap2);
        Map<String,Object> labelMap3=new HashMap<>();
        labelMap3.put("name","信息化建设预算");
        labelMap3.put("value","3000");
        labelMap3.put("unit","亿");
        label.add(labelMap3);
        rt.put("name","智慧型");
        rt.put("list",list);
        rt.put("label",label);
        collection.put("rt",rt);
        list2.put("header",header);
        list2.put("body",body);
        popCllection.put("list2",list2);
        data.put("collection",collection);
        data.put("popCllection",popCllection);
        map.put("code","200");
        map.put("msg","查询成功");
        map.put("data",data);
        return  map;
    }

}
