package awd.cloud.platform.servers.analyse.service.all;


import awd.framework.common.datasource.api.annotation.UseDataSource;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class WXJS_jspfService {


    public Map<String,Object>  jspfQuery(){
        Map<String,Object> cb=new HashMap<>();
        Map<String,Object> map=new HashMap<>();
        Map<String,Object> data=new HashMap<>();
        Map<String,Object> collection=new HashMap<>();
        List< Map<String,Object>>  list=new ArrayList<>();
        Map<String,Object> sj1=new HashMap<>();
        sj1.put("name","北京市第一看守所");
        sj1.put("value","80");
        list.add(sj1);
        Map<String,Object> sj2=new HashMap<>();
        sj2.put("name","北京市第二看守所");
        sj2.put("value","83");
        list.add(sj2);
        Map<String,Object> sj3=new HashMap<>();
        sj3.put("name","北京市第三看守所");
        sj3.put("value","92");
        list.add(sj3);
        Map<String,Object> sj4=new HashMap<>();
        sj4.put("name","北京市第六看守所");
        sj4.put("value","60");
        list.add(sj4);
        Map<String,Object> sj5=new HashMap<>();
        sj5.put("name","东城区看守所");
        sj5.put("value","65");
        list.add(sj5);
        Map<String,Object> sj6=new HashMap<>();
        sj6.put("name","东城区拘留所");
        sj6.put("value","70");
        list.add(sj6);
        Map<String,Object> sj7=new HashMap<>();
        sj7.put("name","西城区看守所");
        sj7.put("value","75");
        list.add(sj7);
        Map<String,Object> sj8=new HashMap<>();
        sj8.put("name","朝阳区看守所");
        sj8.put("value","80");
        list.add(sj8);
        Map<String,Object> sj9=new HashMap<>();
        sj9.put("name","朝阳区拘留所");
        sj9.put("value","85");
        list.add(sj9);
        Map<String,Object> sj10=new HashMap<>();
        sj10.put("name","丰台区看守所");
        sj10.put("value","80");
        list.add(sj10);
        Map<String,Object> sj11=new HashMap<>();
        sj11.put("name","石景山区看守所");
        sj11.put("value","75");
        list.add(sj11);
        Map<String,Object> sj12=new HashMap<>();
        sj12.put("name","海淀区看守所");
        sj12.put("value","80");
        list.add(sj12);
        Map<String,Object> sj13=new HashMap<>();
        sj13.put("name","海淀区拘留所");
        sj13.put("value","75");
        list.add(sj13);
        Map<String,Object> sj14=new HashMap<>();
        sj14.put("name","门头沟区看守所");
        sj14.put("value","80");
        list.add(sj14);
        Map<String,Object> sj15=new HashMap<>();
        sj15.put("name","房山区看守所");
        sj15.put("value","85");
        list.add(sj15);
        Map<String,Object> sj16=new HashMap<>();
        sj16.put("name","房山区第二看守所");
        sj16.put("value","80");
        list.add(sj16);
        Map<String,Object> sj17=new HashMap<>();
        sj17.put("name","房山区拘留所");
        sj17.put("value","85");
        list.add(sj17);
        Map<String,Object> sj18=new HashMap<>();
        sj18.put("name","通州区看守所");
        sj18.put("value","75");
        list.add(sj18);
        Map<String,Object> sj19=new HashMap<>();
        sj19.put("name","顺义区看守所");
        sj19.put("value","65");
        list.add(sj19);
        Map<String,Object> sj20=new HashMap<>();
        sj20.put("name","昌平区看守所");
        sj20.put("value","75");
        list.add(sj20);
        Map<String,Object> sj21=new HashMap<>();
        sj21.put("name","大兴区看守所");
        sj21.put("value","80");
        list.add(sj21);
        Map<String,Object> sj22=new HashMap<>();
        sj22.put("name","平谷区看守所");
        sj22.put("value","75");
        list.add(sj22);
        Map<String,Object> sj23=new HashMap<>();
        sj23.put("name","怀柔区看守所");
        sj23.put("value","80");
        list.add(sj23);
        Map<String,Object> sj24=new HashMap<>();
        sj24.put("name","密云区看守所");
        sj24.put("value","78");
        list.add(sj24);
        Map<String,Object> sj25=new HashMap<>();
        sj25.put("name","延庆区看守所");
        sj25.put("value","80");
        list.add(sj25);
        Map<String,Object> sj26=new HashMap<>();
        sj26.put("name","北京收容教育所");
        sj26.put("value","80");
        list.add(sj26);
        Map<String,Object> sj27=new HashMap<>();
        sj27.put("name","北京市公安局强制隔离戒毒所");
        sj27.put("value","80");
        list.add(sj27);
        cb.put("name","监所评分");
        cb.put("list",list);
        collection.put("cb",cb);
        data.put("collection",collection);
        map.put("code","200");
        map.put("msg","查询成功");
        map.put("data",data);
        return  map;
    }

}
